MAX_BODY_TEMPERATURE = 37
BODY_TEMPERATURE_DECREASE_WHEN_DIGGING = 0.03
BODY_TEMPERATURE_DECREASE_WHEN_NO_ACTION = 0.01
BODY_TEMPERATURE_INCREASE_WHEN_TURN_ON_HEATER = 0.02

MAX_ENERGY = 10
ENERGY_DECREASE_WHEN_DIGGING = 1.6
ENERGY_INCREASE_WHEN_NO_ACTION = 0.5
ENERGY_INCREASE_WHEN_TURN_ON_HEATER = 0.35

MAX_CAR_BATTERY_LEVEL = 5
CAR_BATTERY_DECREASE_WHEN_TURN_ON_HEATER = 0.5

SNOW_DRIFT_SIZE = 20
DIGGING_COEFFICIENT = 0.7
