MAX_BODY_TEMPERATURE = 37
BODY_TEMPERATURE_DECREASE_WHEN_DIGGING = 0.03
BODY_TEMPERATURE_DECREASE_WHEN_NO_ACTION = 0.01
BODY_TEMPERATURE_INCREASE_WHEN_TURN_ON_HEATER = 0.02
BODY_TEMPERATURE_SAVING_THRESHOLD = 36

MAX_ENERGY = 20
ENERGY_DECREASE_WHEN_DIGGING = 1.6
ENERGY_INCREASE_WHEN_NO_ACTION = 1
ENERGY_INCREASE_WHEN_TURN_ON_HEATER = 0.5
ENERGY_SAVING_THRESHOLD = 10

MAX_CAR_BATTERY_LEVEL = 20
CAR_BATTERY_DECREASE_WHEN_TURN_ON_HEATER = 0.5

SNOW_DRIFT_SIZE = 1000
DIGGING_COEFFICIENT = 0.7

EPSILON = 0.7
EXPLOITATION_REWARD = 50
ENERGY_SAVING_REWARD = 100
BODY_TEMPERATURE_SAVING_REWARD = 100


LEARNING_RATE = 1

# TODO: 30 experiments with different seeds with common parameters (minimum, also experiment with parameters)

FILE_NAME = "random"
METADATA_FILE_NAME = "simulation_results/metadata.csv"
